export const companies = [
  {
    id: "tcs",
    name: "TCS",
    fullName: "Tata Consultancy Services",
    description: "India's largest IT services company. Campus hiring includes TCS Ninja, TCS Digital, and TCS Prime.",
    rounds: ["Aptitude", "Technical", "HR"],
    popular: true,
  },
  {
    id: "infosys",
    name: "Infosys",
    fullName: "Infosys Ltd",
    description: "Second-largest IT company in India. Hiring through InfyTQ and campus placements.",
    rounds: ["Aptitude", "Technical", "HR"],
    popular: true,
  },
  {
    id: "wipro",
    name: "Wipro",
    fullName: "Wipro Ltd",
    description: "Leading IT services. Campus hiring through Wipro Elite, Turbo, and WILP programs.",
    rounds: ["Aptitude", "Technical", "HR"],
    popular: true,
  },
  {
    id: "cognizant",
    name: "Cognizant",
    fullName: "Cognizant Technology Solutions",
    description: "Major IT services employer for Indian campuses. Known for CTS hiring process.",
    rounds: ["Aptitude", "Technical", "HR"],
    popular: true,
  },
  {
    id: "accenture",
    name: "Accenture",
    fullName: "Accenture India",
    description: "One of the largest fresher hiring in India. Known for their comprehensive interview process.",
    rounds: ["Aptitude", "Coding", "Technical", "HR"],
    popular: true,
  },
  {
    id: "amazon",
    name: "Amazon",
    fullName: "Amazon India",
    description: "Top product-based company. Known for leadership principles and problem-solving interviews.",
    rounds: ["Online Assessment", "Technical", "Leadership", "HR"],
    popular: false,
  },
  {
    id: "google",
    name: "Google",
    fullName: "Google India",
    description: "The most sought-after tech employer. High standards for problem-solving and system design.",
    rounds: ["Online Assessment", "Technical", "System Design", "Behavioral"],
    popular: false,
  },
];

export const interviewTypes = [
  { id: "hr", name: "HR / Behavioral", description: "Common HR questions, STAR responses, situational" },
  { id: "technical", name: "Technical", description: "Technical concepts, projects, problem-solving" },
  { id: "aptitude", name: "Aptitude", description: "Quantitative, logical reasoning, verbal" },
];

export const hrQuestions: Record<string, string[]> = {
  tcs: [
    "Tell me about yourself.",
    "Why do you want to join TCS?",
    "What are your strengths and weaknesses?",
    "Describe a time you worked in a team to achieve a goal.",
    "Where do you see yourself in 5 years?",
    "Tell me about a time you faced a challenge and how you overcame it.",
    "Why should we hire you?",
    "What do you know about TCS's values?",
    "Describe a situation where you showed leadership.",
    "How do you handle pressure or stressful situations?",
  ],
  infosys: [
    "Tell me about yourself.",
    "Why Infosys?",
    "What are your career goals?",
    "Describe a project you're proud of.",
    "How do you handle feedback?",
    "Tell me about a time you went above and beyond.",
    "What do you know about Infosys?",
    "Describe a time you made a mistake and how you handled it.",
    "How do you prioritize your work?",
    "Why should we select you?",
  ],
  wipro: [
    "Introduce yourself.",
    "Why do you want to work at Wipro?",
    "What are your long-term career aspirations?",
    "Tell me about a time you worked under a tight deadline.",
    "What do you know about Wipro's services?",
    "Describe a time you resolved a conflict.",
    "What makes you different from other candidates?",
    "Tell me about a time you learned something new quickly.",
    "How do you stay motivated?",
    "Describe your ideal work environment.",
  ],
  cognizant: [
    "Tell us about yourself.",
    "Why Cognizant?",
    "What are your expectations from this role?",
    "Describe a time you adapted to change.",
    "What do you know about Cognizant?",
    "Tell me about a time you helped someone.",
    "How do you handle multiple tasks?",
    "Describe a situation where you had to persuade others.",
    "What is your greatest achievement?",
    "Where do you see yourself in 5 years?",
  ],
  accenture: [
    "Tell me about yourself.",
    "Why Accenture?",
    "What do you know about Accenture's culture?",
    "Describe a time you delivered results under pressure.",
    "Tell me about a time you worked on a team project.",
    "What are your salary expectations?",
    "How do you deal with ambiguity?",
    "Describe a time you showed initiative.",
    "What skills do you bring to Accenture?",
    "Tell me about a time you failed and what you learned.",
  ],
  amazon: [
    "Tell me about yourself.",
    "Why Amazon?",
    "Describe a situation where you thought big.",
    "Tell me about a time you delivered results against tight deadlines.",
    "Describe a time you took a calculated risk.",
    "How do you handle disagreements with team members?",
    "Tell me about your most challenging project.",
    "Describe a time you went above and beyond for a customer.",
    "How do you prioritize competing tasks?",
    "Tell me about a time you learned from a failure.",
  ],
  google: [
    "Tell me about yourself.",
    "Why Google?",
    "What is your biggest professional achievement?",
    "Describe a time you solved a complex problem.",
    "Tell me about a time you influenced a team decision.",
    "How do you handle ambiguity?",
    "Describe a project from start to finish.",
    "Tell me about a time you disagreed with a manager.",
    "What would you do in your first 30 days at Google?",
    "Describe a time you were not satisfied with the status quo.",
  ],
};

export function getQuestionsForCompany(companyId: string, type: string): string[] {
  if (type === "hr" || type === "behavioral") {
    return hrQuestions[companyId] || hrQuestions["tcs"];
  }
  return hrQuestions["tcs"];
}
